openapi: 3.0.1
info:
  description: Telemetry Service Credential APIs.
  title: Credential API
  version: v1alpha
paths:
  /v1alpha/sas-token:
    get:
      description: Return a SAS token for publishing telemetry records.
      operationId: generateToken
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
      responses:
        "200":
          description: Token was generated successfully.
        "400":
          description: Request body was malformed
        "500":
          description: Server failed to generate token
components:
  schemas:
    TokenRepresentation:
      type: object
      properties:
        additional:
          type: object
          additionalProperties:
            type: object
        expiresIn:
          type: integer
          format: int64
        token:
          type: string
