openapi: 3.0.1
info:
  description: With this API clients can retire an active Contract Agreement. Clients
    can also list all retired agreements.
  title: Agreements Retirement API
paths:
  /v3/contractagreements/retirements:
    post:
      description: Retires an active contract agreement.
      operationId: retireAgreementV3
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Retirement Example"
      responses:
        "204":
          description: The contract agreement was successfully retired
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Request body was malformed
        "409":
          description: The contract agreement is already retired
      tags:
      - Agreements Retirement
  /v3/contractagreements/retirements/request:
    post:
      description: Get all retired contract agreements.
      operationId: getAllRetiredV3
      responses:
        "200":
          description: A list of retired contract agreements
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Request body was malformed
      tags:
      - Agreements Retirement
  /v3/contractagreements/retirements/{agreementId}:
    delete:
      description: "Removes a contract agreement from the retired list, reactivating\
        \ it."
      operationId: reactivateRetiredV3
      parameters:
      - description: The contract agreement id
        in: path
        name: agreementId
        required: true
        schema:
          type: string
      responses:
        "204":
          description: The contract agreement is reactivated
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Request body was malformed
        "404":
          description: No entry for the given agreementId was found
      tags:
      - Agreements Retirement
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: object
        message:
          type: string
        path:
          type: string
        type:
          type: string
    JsonArray:
      type: array
      items:
        $ref: "#/components/schemas/JsonValue"
      properties:
        empty:
          type: boolean
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    JsonObject:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/JsonValue"
      properties:
        empty:
          type: boolean
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    Retirement Example:
      type: object
      example:
        '@context':
          eonax: https://w3id.org/eonax/v0.0.1/ns/
          edc: https://w3id.org/edc/v0.0.1/ns/
        edc:agreementId: contract-agreement-id
        eonax:reason: This contract agreement was retired since the physical counterpart
          is no longer valid.
      properties:
        '@id':
          type: string
        reason:
          type: string
