@startuml
entity edc_telemetry_record {
  * record_id: string <<PK>>
  * properties: string <<json>>
  * state: int
  * state_count: int
  * state_time_stamp: long
  * created_at: long
  * updated_at: long
  * trace_context: string <<json>>
  * error_detail: string
  --
}
@enduml